# Generated by Django 3.2.4 on 2022-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220113_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='comment',
            field=models.TextField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
    ]
