version: "3.3"

services:
  db:
    image: postgres:13-alpine3.14
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    depends_on:
      - db
    